//  An array of available fonts for the app

export const fonts: {
  label: string;
  value: string;
}[] = [
  { label: "Arial", value: "Arial" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Courier New", value: "Courier New" },
  { label: "Georgia", value: "Georgia" },
  { label: "Verdana", value: "Verdana" },
  { label: "Roboto", value: "Roboto" },
  { label: "Open Sans", value: "Open Sans" },
  { label: "Lato", value: "Lato" },
  { label: "Montserrat", value: "Montserrat" },
  { label: "Poppins", value: "Poppins" },
  { label: "Merriweather", value: "Merriweather" },
  { label: "Playfair Display", value: "Playfair Display" },
  { label: "Raleway", value: "Raleway" },
  { label: "Source Sans Pro", value: "Source Sans Pro" },
  { label: "Oswald", value: "Oswald" },
  { label: "Ubuntu", value: "Ubuntu" },
  { label: "Nunito", value: "Nunito" },
  { label: "PT Sans", value: "PT Sans" },
  { label: "PT Serif", value: "PT Serif" },
  { label: "Noto Sans", value: "Noto Sans" },
  { label: "Noto Serif", value: "Noto Serif" },
  { label: "Dancing Script", value: "Dancing Script" },
  { label: "Pacifico", value: "Pacifico" },
  { label: "Indie Flower", value: "Indie Flower" },
  { label: "Shadows Into Light", value: "Shadows Into Light" },
  { label: "Amatic SC", value: "Amatic SC" },
  { label: "Bebas Neue", value: "Bebas Neue" },
  { label: "Caveat", value: "Caveat" },
  { label: "Comfortaa", value: "Comfortaa" },
  { label: "Exo 2", value: "Exo 2" },
  { label: "Fira Sans", value: "Fira Sans" },
  { label: "Josefin Sans", value: "Josefin Sans" },
  { label: "Lobster", value: "Lobster" },
  { label: "Mukta", value: "Mukta" },
  { label: "Quicksand", value: "Quicksand" },
  { label: "Rubik", value: "Rubik" },
  { label: "Titillium Web", value: "Titillium Web" },
  { label: "Work Sans", value: "Work Sans" },
  { label: "Yanone Kaffeesatz", value: "Yanone Kaffeesatz" },
  { label: "Zilla Slab", value: "Zilla Slab" },
  { label: "Crimson Text", value: "Crimson Text" },
  { label: "Libre Baskerville", value: "Libre Baskerville" },
  { label: "Abril Fatface", value: "Abril Fatface" },
  { label: "Archivo", value: "Archivo" },
  { label: "Arvo", value: "Arvo" },
  { label: "Bitter", value: "Bitter" },
  { label: "Cardo", value: "Cardo" },
  { label: "Domine", value: "Domine" },
  { label: "EB Garamond", value: "EB Garamond" },
  { label: "Faustina", value: "Faustina" },
  { label: "Inconsolata", value: "Inconsolata" },
  { label: "Inter", value: "Inter" },
  { label: "Karla", value: "Karla" },
  { label: "Lora", value: "Lora" },
  { label: "Manrope", value: "Manrope" },
  { label: "Old Standard TT", value: "Old Standard TT" },
  { label: "Overpass", value: "Overpass" },
  { label: "Piazzolla", value: "Piazzolla" },
  { label: "Prata", value: "Prata" },
  { label: "Red Hat Display", value: "Red Hat Display" },
  { label: "Space Mono", value: "Space Mono" },
  { label: "Spectral", value: "Spectral" },
  { label: "Suez One", value: "Suez One" },
  { label: "Vollkorn", value: "Vollkorn" },
  { label: "Alegreya", value: "Alegreya" },
  { label: "Alegreya Sans", value: "Alegreya Sans" },
  { label: "Asap", value: "Asap" },
  { label: "BioRhyme", value: "BioRhyme" },
  { label: "Cabin", value: "Cabin" },
  { label: "Chivo", value: "Chivo" },
  { label: "Cormorant", value: "Cormorant" },
  { label: "DM Sans", value: "DM Sans" },
  { label: "DM Serif Display", value: "DM Serif Display" },
  { label: "Fjalla One", value: "Fjalla One" },
  { label: "Frank Ruhl Libre", value: "Frank Ruhl Libre" },
  { label: "Heebo", value: "Heebo" },
  { label: "IBM Plex Sans", value: "IBM Plex Sans" },
  { label: "IBM Plex Serif", value: "IBM Plex Serif" },
  { label: "Kreon", value: "Kreon" },
  { label: "Literata", value: "Literata" },
  { label: "Maven Pro", value: "Maven Pro" },
  { label: "Nanum Gothic", value: "Nanum Gothic" },
  { label: "Nanum Myeongjo", value: "Nanum Myeongjo" },
  { label: "Newsreader", value: "Newsreader" },
  { label: "Noticia Text", value: "Noticia Text" },
  { label: "Nunito Sans", value: "Nunito Sans" },
  { label: "Philosopher", value: "Philosopher" },
  { label: "Proza Libre", value: "Proza Libre" },
  { label: "Public Sans", value: "Public Sans" },
  { label: "Sen", value: "Sen" },
  { label: "Source Code Pro", value: "Source Code Pro" },
  { label: "Spartan", value: "Spartan" },
  { label: "Spectral SC", value: "Spectral SC" },
  { label: "Syne", value: "Syne" },
  { label: "Taviraj", value: "Taviraj" },
  { label: "Trirong", value: "Trirong" },
  { label: "Volkhov", value: "Volkhov" },
  { label: "Yrsa", value: "Yrsa" },
];

// An array of availabel headings level for the app
export const headings: {
  label: string;
  value: number;
  fontSize: string;
}[] = [
  { label: "Normal Text", value: 0, fontSize: "16px" },
  { label: "Heading 1", value: 1, fontSize: "32px" },
  { label: "Heading 2", value: 2, fontSize: "24px" },
  { label: "Heading 3", value: 3, fontSize: "20px" },
  { label: "Heading 4", value: 4, fontSize: "18px" },
  { label: "Heading 5", value: 5, fontSize: "16px" },
];

// Templates for the app home page

export const templates: {
  id: string;
  label: string;
  imageSrc: string;
}[] = [
  {
    id: "blank",
    label: "Blank document",
    imageSrc: "./assets/blank-document.svg",
  },
  {
    id: "business-letter",
    label: "Business letter",
    imageSrc: "./assets/business-letter.svg",
  },
  {
    id: "cover-letter",
    label: "Cover letter",
    imageSrc: "./assets/cover-letter.svg",
  },
  {
    id: "letter",
    label: "Letter",
    imageSrc: "./assets/letter.svg",
  },
  {
    id: "project-proposal",
    label: "Project proposal",
    imageSrc: "./assets/project-proposal.svg",
  },
  {
    id: "resume",
    label: "Resume",
    imageSrc: "./assets/resume.svg",
  },
  {
    id: "software-proposal",
    label: "Software proposal",
    imageSrc: "./assets/software-proposal.svg",
  },
];
